# Generated by `rjournal_article()` using `knitr::purl()`: do not edit by hand
# Please edit manuscript.Rmd to modify this file

## ---- echo = FALSE------------------------------------------------------------
knitr::opts_chunk$set(fig.height = 4, message = FALSE, warning = FALSE)


## -----------------------------------------------------------------------------
library(pald)
df <- data.frame(
  x1 = c(6, 8, 11, 16, 4),
  x2 = c(5, 4, 13, 7, 18)
)
rownames(df) <- c("A", "B", "C", "D", "E")


## -----------------------------------------------------------------------------
d <- dist(df)


## -----------------------------------------------------------------------------
d <- dist(df)
cohesion_matrix(d)


## -----------------------------------------------------------------------------
df |>
  dist() |>
  cohesion_matrix()


## -----------------------------------------------------------------------------
d |>
  dist() |>
  cohesion_matrix() -> cohesion


## -----------------------------------------------------------------------------
community_clusters(cohesion)


## -----------------------------------------------------------------------------
local_depths(cohesion)


## -----------------------------------------------------------------------------
strong_threshold(cohesion)


## -----------------------------------------------------------------------------
any_isolated(cohesion)


## -----------------------------------------------------------------------------
cohesion_strong(cohesion)


## -----------------------------------------------------------------------------
graphs <- community_graphs(cohesion)
graphs[["G_strong"]]


## ----fig1, fig.cap = "Visualize the points from data frame `df`", message = FALSE, warning = FALSE----
library(ggplot2)
ggplot(df, aes(x1, x2)) +
  geom_text(label = rownames(df))


## ----fig2, fig.cap = "PaLD graph displaying the relationship between the points in data frame `df`"----
df |>
  dist() |>
  cohesion_matrix() |>
  plot_community_graphs()


## ----fig3, fig.cap = "PaLD graph displaying the relationship between the points in data frame `d`, matching the original layout in Figure 1"----
df |>
  dist() |>
  cohesion_matrix() |>
  plot_community_graphs(layout = as.matrix(df))


## ----fig4, fig.cap = "PaLD graph displaying the relationship between the points in data frame `d`, matching the original layout in Figure 1, adding axes"----
df |>
  dist() |>
  cohesion_matrix() |>
  plot_community_graphs(layout = as.matrix(df),
                        axes = TRUE)


## ----fig5, fig.cap = "PaLD clustering of tissue data", fig.height = 9, fig.width = 7----
set.seed(1)

labels <- rownames(tissue_cohesion_matrix)
labels[sample(1:189, 125)] <- ""
plot_community_graphs(tissue_cohesion_matrix,
                      vertex.label = labels,
                      vertex.size = 4)


## -----------------------------------------------------------------------------
library(dplyr)
community_clusters(tissue_cohesion_matrix) %>%
  group_by(cluster, point) %>%
  count()


## -----------------------------------------------------------------------------
exdata_cohesion_matrix <- exdata3 |>
  dist() |>
  cohesion_matrix()


## ----fig6, fig.cap = "PaLD clustering of randomly generated example data (from Figure 4D from Berenhaut et al. (2022))"----
plot_community_graphs(exdata_cohesion_matrix,
                layout = as.matrix(exdata3),
                show_labels = FALSE, 
                only_strong = TRUE,
                vertex.size = 5)

